name: Build Jekyll site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Set safe directory
      run: git config --global --add safe.directory /github/workspace

    - name: Install dependencies
      run: bundle install

    - name: Build site
      run: bundle exec jekyll build